name: PR Build Check

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --no-restore

      # Skicka meddelande om build lyckades
      - name: Notify Discord - Success
        if: success()
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: success
          title: "✅ PR Build Passed"
          description: |
            PR #${{ github.event.pull_request.number }} by ${{ github.actor }}
            Build succeeded 🎉
          color: 0x00ff00

      # Skicka meddelande om bygget misslyckades
      - name: Notify Discord - Failure
        if: failure()
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: failure
          title: "❌ PR Build Failed"
          description: |
            PR #${{ github.event.pull_request.number }} by ${{ github.actor }}
            Build failed 💥
          color: 0xff0000